# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Main Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.PAT_DOCKER_TP_DEVOPS }}
      - name: Build, tag and push Docker image
        run: |
          docker build -t docker.io/kflandry/tp-final-frontend:latest -f ./frontend/Dockerfile ./
          docker tag docker.io/kflandry/tp-final-frontend:latest docker.io/kflandry/tp-final-frontend:$GITHUB_SHA
          docker push docker.io/kflandry/tp-final-frontend:latest
          docker push docker.io/kflandry/tp-final-frontend:$GITHUB_SHA

          docker build -t docker.io/kflandry/tp-final-backend:latest -f ./backend/Dockerfile ./
          docker tag docker.io/kflandry/tp-final-backend:latest docker.io/kflandry/tp-final-backend:$GITHUB_SHA
          docker push docker.io/kflandry/tp-final-backend:latest
          docker push docker.io/kflandry/tp-final-backend:$GITHUB_SHA

  deploy_on_render_backend:
    runs-on: ubuntu-latest
    needs: docker_push
    steps:
      - name: Deploy to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.3
        with:
          deploy-hook: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
          image-url: docker.io/kflandry/tp-final-backend:latest
          render-api-key: ${{ secrets.RENDER_API_KEY_PROD }}
          wait-for-deployment: true

  deploy_on_render_frontend:
    runs-on: ubuntu-latest
    needs: [docker_push, deploy_on_render_backend]
    steps:
      - name: Deploy to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.3
        with:
          deploy-hook: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
          image-url: docker.io/kflandry/tp-final-frontend:latest
          render-api-key: ${{ secrets.RENDER_API_KEY_PROD }}
          wait-for-deployment: true
